name: Pipeline
on:
  push:
    branches:
    - '*'
  pull_request:
jobs:
  lint:
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4.1.7
    - uses: luizm/action-sh-checker@v0.3.0
      env:
        SHFMT_OPTS: -s
      with:
        sh_checker_comment: true

  lint-markdown:
    uses: PurpleBooth/common-pipelines/.github/workflows/markdown-check.yml@main
    
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4.1.7
    - uses: mig4/setup-bats@v1
    - run: sudo apt-get install pandoc
    - run: make test

  commit-checks:
    uses: PurpleBooth/common-pipelines/.github/workflows/commit-check.yml@main
    
  release:
    if: github.ref == 'refs/heads/main'
    needs:
    - lint
    - test
    - commit-checks
    - lint-markdown
    outputs:
      current_version: ${{ steps.current_version.outputs.current_version }}
      previous_version: ${{ steps.previous_version.outputs.previous_version }}
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@main
      with:
        fetch-depth: 0
    - uses: cargo-bins/cargo-binstall@main
      name: Install cargo binstall
    - name: Get tags
      run: git fetch --tags origin
    - shell: bash
      run: cargo binstall --no-confirm --locked cocogitto
    - id: previous_version
      run: |
        cog get-version | tee .version
        echo "previous_version=$( cat .version )"  >> "$GITHUB_OUTPUT"
        rm .version
      shell: bash
    - name: Semver release
      id: release
      run: |
        git config --global user.name "cog-bot"
        git config --global user.email "cog@example.com"
        cog bump --auto
    - id: current_version
      run: |
        cog get-version | tee .version
        echo "current_version=$( cat .version )"  >> "$GITHUB_OUTPUT"
        rm .version
      shell: bash

  upload-release:
    if: needs.release.outputs.current_version != needs.release.outputs.previous_version
    needs:
    - release
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4.1.7
      name: Checkout the repository
      with:
        lfs: true
        fetch-depth: 0
        ref: v${{ needs.release.outputs.current_version }}
    - id: get_repository_name
      name: Calculate repository name
      run: echo ::set-output name=REPOSITORY_NAME::$(echo "$GITHUB_REPOSITORY" | awk
        -F / '{print $2}' | sed -e "s/:refs//")
      shell: bash
    - uses: dlavrenuek/conventional-changelog-action@v1.1.2
      id: changelog
      with:
        from: v${{ needs.release.outputs.previous_version }}
        to: v${{ needs.release.outputs.current_version }}
    - env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      id: create_release
      uses: ncipollo/release-action@2c591bcc8ecdcd2db72b97d6147f871fcd833ba5 # v1.14.0
      with:
        artifacts: "gfmfmt"
        allowUpdates: true
        token: ${{ secrets.GITHUB_TOKEN }}
        body: ${{ steps.changelog.outputs.body }}
        name: Release v${{ needs.release.outputs.current_version }}
        tag: v${{ needs.release.outputs.current_version }}

  generate-formula:
    if: needs.release.outputs.current_version != needs.release.outputs.previous_version
    needs:
      - release
    name: Generate Homebrew Formula
    runs-on: ubuntu-latest
    steps:
      - id: get_repository_name
        name: Work out repository name
        run:
          echo ::set-output "name=REPOSITORY_NAME::$(echo "$GITHUB_REPOSITORY" |
          awk -F / '{print $2}' | sed -e "s/:refs//")"
        shell: bash
      - uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4.1.7
        name: Checkout this repository
        with:
          path: main-repo
          ref: v${{ needs.release.outputs.current_version }}
      - name: Import GPG key
        uses: crazy-max/ghaction-import-gpg@v3.1.0
        with:
          gpg-private-key: ${{ secrets.GPG_PRIVATE_KEY }}
          passphrase: ${{ secrets.GPG_PASSPHRASE }}
          git-user-signingkey: true
          git-commit-gpgsign: true
          git-tag-gpgsign: true
          workdir: main-repo
      - uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4.1.7
        with:
          repository: PurpleBooth/homebrew-repo
          token: ${{ secrets.COMMITTER_TOKEN }}
          path: homebrew-repo
          ref: main
        name: Checkout the custom tap
      - name: Import GPG key
        uses: crazy-max/ghaction-import-gpg@v3.1.0
        with:
          gpg-private-key: ${{ secrets.GPG_PRIVATE_KEY }}
          passphrase: ${{ secrets.GPG_PASSPHRASE }}
          git-user-signingkey: true
          git-commit-gpgsign: true
          git-tag-gpgsign: true
          workdir: homebrew-repo
      - run: |
          curl -Lo file.tar.gz "https://github.com/$GIT_REPO/archive/$GIT_TAG.tar.gz"
          sha256sum -b file.tar.gz | awk '{ print $1 }' > hash
          echo ::set-output "name=SHA256::$( cat hash )"
        id: hash
        shell: bash
        env:
          GIT_REPO: ${{ github.repository }}
          GIT_TAG: v${{ needs.release.outputs.current_version }}
        name: Calculate the binary hash
      - uses: cuchi/jinja2-action@v1.2.0
        with:
          template: main-repo/homebrew/formula.rb.j2
          output_file: formula.rb
          variables: |
            github_repo=${{ github.repository }}
            git_tag=v${{ needs.release.outputs.current_version }}
            file_sha=${{ steps.hash.outputs.SHA256 }}
        name: Generate the template
      - shell: bash
        name: Open a PR on the custom tap repository
        run: |
          VERSION="$(echo $GIT_TAG | sed 's/^refs\/tags\///')"
          git -C homebrew-repo switch -c "$REPOSITORY_NAME-$VERSION"
          cp formula.rb "homebrew-repo/Formula/$REPOSITORY_NAME.rb"
          git -C homebrew-repo add "Formula/$REPOSITORY_NAME.rb"
          git -C homebrew-repo commit -m "fix: Update $REPOSITORY_NAME to $VERSION"
          git -C homebrew-repo push origin "$REPOSITORY_NAME-$VERSION"
          (cd homebrew-repo && gh pr create --label releases --base main --fill)
        env:
          REPOSITORY_NAME: ${{ steps.get_repository_name.outputs.REPOSITORY_NAME }}
          GIT_TAG: v${{ needs.release.outputs.current_version }}
          GITHUB_TOKEN: ${{ secrets.COMMITTER_TOKEN }}
